### PR TITLE
Adds composer.json

### PR DESCRIPTION
**Pull request by juho-jaakkola**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
I didn't add license info because I didn't find one from the plugin.

**Comment by juho-jaakkola** [comment]
The [library](https://github.com/xoxco/jQuery-Tags-Input/blob/master/package.json#L17) is using ISC license. Perhaps the plugin should use the same?

**Comment by mrclay** [comment]
Adding ISC is fine with me.

**Comment by mrclay** [comment]
I've added you as collaborator, so feel free to make improvements :+1:

**Comment by juho-jaakkola** [comment]
Thanks!

**Pull request merged**
